# Site settings
title: Vinpa
email: "vinpa.web@gmail.com"
description: Vinpa Web
url: "http://pkpacheco.github.io"
baseurl: "/vinpa"

# twitter_username: pyladies_mendoza
github_username: PKpacheco

# Build settings
markdown: kramdown

highlighter: green

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"

collections:
  home:
    output: true
    permalink: /home/:path/
  contact:
    output: true
    permalink: /contact/:path/
 